version: 2.1
orbs:
  android: circleci/android@1.0
commands:
  use-cached-ndk:
    parameters:
      ndk-version:
        description: Download NDK
        type: string
      android-ndk-root-path:
        description: Android NDK root path
        type: string
        default: /opt/android/sdk/ndk
      cache-prefix:
        description: Used to form part of the cache key
        type: string
        default: v1
    steps:
      - run:
          name: install pigz
          command: sudo apt update && sudo apt install pigz
      - restore_cache:
          name: Restore NDK <<parameters.ndk-version>> cache
          key: <<parameters.cache-prefix>>-{{ arch }}-<<parameters.ndk-version>>
          paths:
            - <<parameters.android-ndk-root-path>>/<<parameters.ndk-version>>
      - run:
          command: |
            if [ -f ndk.tar.gz ]; then
              tar xvf ndk.tar.gz --use-compress-prog=pigz
              mv opt/android/sdk/ndk/<<parameters.ndk-version>> /opt/android/sdk/ndk/<<parameters.ndk-version>>
            fi
      - run:
          name: Download ndk version for caching if not exists
          command: |
            if [ ! -d "<<parameters.android-ndk-root-path>>/<<parameters.ndk-version>>" ]
            then
                echo "Download NDK version for caching"
                sdkmanager "ndk;<<parameters.ndk-version>>"
            fi
      - run: tar cv --use-compress-program pigz -f ndk.tar.gz /opt/android/sdk/ndk/<<parameters.ndk-version>>
      - save_cache:
          name: Save NDK <<parameters.ndk-version>> cache
          key: << parameters.cache-prefix>>-{{ arch }}-<<parameters.ndk-version>>
          paths:
            - <<parameters.android-ndk-root-path>>/<<parameters.ndk-version>>
jobs:
  test:
    executor:
      name: android/android-machine
      resource-class: medium
    parallelism: 2
    steps:
      - use-cached-ndk:
          ndk-version: "22.1.7171670"

workflows:
  test1:
    triggers:
      - schedule:
          cron: "23 * * * *"
          filters:
            branches:
              only:
                - main
                - jkg/circleci_test_deletedbranch_cronjob
    jobs:
      - test
  test2:
    triggers:
      - schedule:
          cron: "24 * * * *"
          filters:
            branches:
              only:
                - main
                - jkg/circleci_test_deletedbranch_cronjob
    jobs:
      - test
  
  build:
    jobs:
      - test
