version: 2.1
orbs:
  android: circleci/android@1.0.3
commands:
  use-cached-ndk:
    parameters:
      ndk-version:
        description: Download NDK
        type: string
      android-ndk-root-path:
        description: Android NDK root path
        type: string
        default: /opt/android/sdk/ndk
      cache-prefix:
        description: Used to form part of the cache key
        type: string
        default: v1
    steps:
      - restore_cache:
          name: Restore NDK <<parameters.ndk-version>> cache
          key: <<parameters.cache-prefix>>-{{ arch }}-<<parameters.ndk-version>>
          paths:
            - <<parameters.android-ndk-root-path>>/<<parameters.ndk-version>>
      - run:
          name: Download ndk version for caching if not exists
          command: |
            if [ ! -d "<<parameters.android-ndk-root-path>>/<<parameters.ndk-version>>" ]
            then
                echo "Download NDK version for caching"
                sdkmanager "ndk;<<parameters.ndk-version>>"
            fi
      - save_cache:
          name: Save NDK <<parameters.ndk-version>> cache
          key: << parameters.cache-prefix>>-{{ arch }}-<<parameters.ndk-version>>
          paths:
            - <<parameters.android-ndk-root-path>>/<<parameters.ndk-version>>
jobs:
  test:
    executor:
      name: android/android-machine
      resource-class: medium
    parallelism: 2
    steps:
      - use-cached-ndk:
          ndk-version: "21.4.7075529"

workflows:
  build:
    jobs:
      - test
